apiVersion: v1
kind: PersistentVolume
metadata:
  name: hugo-volume
  namespace: clo4
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/hugo"
