apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hugo-claim
  namespace: clo4
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
