apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: hugo
  namespace: clo4
spec:
  ports:
    - name: "1313"
      port: 1313
      targetPort: 1313
  selector:
    app: wordpress
    tier: documentation
