apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress
  namespace: clo4
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 80
  selector:
    app: wordpress
    tier: frontend
